name: Build with PyInstaller

on:
  workflow_dispatch:
    inputs:
      py_version:
        description: 'Python version to use'
        required: true
        default: '3.8'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            pyinstaller-extra-args: ""
          - os: macos-latest
            pyinstaller-extra-args: ""
          - os: windows-latest
            pyinstaller-extra-args: ""
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ github.event.inputs.py_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Run PyInstaller
      run: |
        pyinstaller --onefile your_script.py ${{ matrix.pyinstaller-extra-args }}
      # Replace 'your_script.py' with the entry point of your application

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: executable-${{ matrix.os }}
        path: dist/