name: Build with PyInstaller

on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.9'
          spec: 'main.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: "vigilant-${{ matrix.os }}-${{ github.sha }}"
          options: "--onefile, --name 'vigilant-${{ matrix.os }}-${{ github.sha }}'"
